#!/usr/bin/python3

import socket
import argparse


def main():
    
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument('--server_ip', type=str, default='localhost', help='ip address of the server')
    arg_parser.add_argument('--server_port', type=int, default=1234, help='port of the server')
    arg_parser.add_argument('-v', '--verbose', action='store_true', help='verbose output of qstat')
    args = arg_parser.parse_args()

    server_address = (args.server_ip, args.server_port)
    verbose = 'verbose' if args.verbose else 'quiet'
    
    print(f"Attempting to connect to {args.server_ip} on port {args.server_port}")

    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(10.0)  # Timeout for socket operations like connect
        print("Socket created, setting timeout to 10 seconds.")

        sock.connect(server_address)
        print("Connection established.")

        request_message = 'qstat:' + verbose
        sock.sendall(request_message.encode())  # Ensure string is encoded to bytes
        print(f"Sent data: {request_message}")

        if not args.verbose:
            print('+----------------------------------------------------------------------------+')
            print('|id               jobname    submit/start time  status         user  priority|')
            print('+----------------------------------------------------------------------------+')
        else:
            print('+-----------------------------------------------------------------------------------------------------------------+')
            print('|id               jobname    submit/start time  status         user  priority  threads    memory  time limit  gpus|')
            print('+-----------------------------------------------------------------------------------------------------------------+')

        reply = sock.recv(1024).decode()  # Decode bytes back to string
        while reply:
            print(f"Received: {reply}")
            sock.sendall('ack'.encode())  # Send acknowledgement
            reply = sock.recv(1024).decode()
        


        if not args.verbose:
            print('+----------------------------------------------------------------------------+')
        else:
            print('+-----------------------------------------------------------------------------------------------------------------+')
    
        print("All data received. Closing socket.")
        sock.close()

    except Exception as e:
        print(f'qstat: no answer from server - Error: {e}')


if __name__ == '__main__':
    main()
