#!/usr/bin/python3

import argparse
import os
import subprocess
import signal
import socket
from block_parser import Block_Parser

def run_locally(block, args, subtask_id):
    tmp_script_file = '.' + block.values['name'] + '.' + str(subtask_id + 1) + '.local'
    with open(tmp_script_file, 'w') as f:
        f.write('#!/bin/bash\n')
        f.write('export N_SUBTASKS=' + str(block.values['subtasks']) + '\n')
        f.write('export SUBTASK_ID=' + str(subtask_id+1) + '\n')
        f.write('\n'.join(block.values['script']))
    print(f"Executing locally: bash {tmp_script_file} {' '.join(args)}")
    subprocess.call(['bash'] + [tmp_script_file] + args)
    os.remove(tmp_script_file)

def request_id(server_address):
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(10.0)
        print(f"Connecting to server at {server_address}")
        sock.connect(server_address)
        sock.sendall('get_id'.encode())
        job_id = int(sock.recv(1024).decode())
        sock.close()
        print(f"Received job ID: {job_id}")
    except Exception as e:
        print(f'request id: no answer from server - Error: {str(e)}')
        exit()
    return job_id

def submit_job(script, server_address, block_idx, job_id, subtask_id, depends_on):
    script_str = ' '.join(script)
    args = (f" --server_ip={server_address[0]} --server_port={str(server_address[1])}"
            f" --block_index={str(block_idx)} --job_id={str(job_id)}"
            f" --subtask_id={str(subtask_id)} --user={os.getenv('USER')}")
    if depends_on:
        args += ' --depends_on=' + ','.join(map(str, depends_on))
    command = f"job.py{args} {script_str} &"
    print(f"Submitting job with command: {command}")
    os.system(command)

def select_blocks(script, start_block, only_start_block=False):
    b = Block_Parser()
    blocks = b.parse(script)
    start_idx = 0
    for block in blocks:
        if block.values['name'] == start_block:
            break
        start_idx += 1
    if start_idx >= len(blocks):
        print(f'Block name {start_block} does not exist. Do not submit jobs.')
        exit()
    block_range = range(start_idx, start_idx+1) if only_start_block else range(start_idx, len(blocks))
    return blocks, block_range

def main():
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument('script', type=str, nargs='+', help='Script (plus its parameters) to be submitted. Include script parameters that start with a dash by escaping them.')
    arg_parser.add_argument('-l', '--local', action='store_true', help='Execute the script locally')
    group = arg_parser.add_mutually_exclusive_group()
    group.add_argument('-b', '--block', type=str, default='', help='Only submit/execute the specified block')
    group.add_argument('-s', '--subtask', type=str, default='', nargs=2, help='Submit/execute the specified block subtask.')
    group.add_argument('-f', '--from_block', type=str, default='', help='Start from the specified block.')
    arg_parser.add_argument('--server_ip', type=str, default='localhost', help='IP address of the server')
    arg_parser.add_argument('--server_port', type=int, default=1234, help='Port of the server')
    args = arg_parser.parse_args()

    server_address = (args.server_ip, args.server_port)

    if args.block:
        blocks, block_indices = select_blocks(args.script[0], args.block, True)
    elif args.subtask:
        blocks, block_indices = select_blocks(args.script[0], args.subtask[0], True)
        try:
            subtask_id = int(args.subtask[1])
            assert subtask_id <= blocks[block_indices[0]].values['subtasks'] and subtask_id > 0
        except Exception as e:
            print(f'Subtask error: {str(e)}')
            exit()
    elif args.from_block:
        blocks, block_indices = select_blocks(args.script[0], args.from_block, False)
    else:
        blocks, block_indices = select_blocks(args.script[0], '', False)

    if args.local:
        for block_idx in block_indices:
            subtask_ids = range(blocks[block_idx].values['subtasks']) if not args.subtask else [int(args.subtask[1]) - 1]
            for subtask_id in subtask_ids:
                run_locally(blocks[block_idx], args.script[1:], subtask_id)
    else:
        depends_on = []
        for block_idx in block_indices:
            block_job_ids = []
            subtask_ids = range(blocks[block_idx].values['subtasks']) if not args.subtask else [int(args.subtask[1]) - 1]
            for subtask_id in subtask_ids:
                job_id = request_id(server_address)
                block_job_ids.append(job_id)
                submit_job(args.script, server_address, block_idx, job_id, subtask_id, depends_on)
            depends_on = block_job_ids

if __name__ == '__main__':
    main()
